services:
  garmin-kit:
    build: .
    container_name: garmin-tools-kit
    volumes:
      - ./client:/app/client
      - ./models:/app/models
      - ./data:/app/data
      - ./example:/app/example
      - ./test_data:/app/test_data
      - ./tests:/app/tests
      - ./.garth:/app/.garth
      - ./activity.py:/app/activity.py
      - ./workout.py:/app/workout.py
      - ./requirements.txt:/app/requirements.txt
      - ./GEMINI.md:/app/GEMINI.md
    environment:
      - TZ=Asia/Taipei
    stdin_open: true          # 保持交互式介面
    tty: true                 # 分配 TTY
    working_dir: /app
